/** Audit event names (§30). Extend rather than inventing ad-hoc strings. */
export const AUDIT_ACTIONS = {
  LOGIN: 'LOGIN',
  OTP_VERIFIED: 'OTP_VERIFIED',
  PROFILE_CREATED: 'PROFILE_CREATED',
  PROFILE_UPDATED: 'PROFILE_UPDATED',

  // Registration lifecycle
  REGISTRATION_STARTED: 'REGISTRATION_STARTED',
  REGISTRATION_SECTION_SAVED: 'REGISTRATION_SECTION_SAVED',
  REGISTRATION_SUBMITTED: 'REGISTRATION_SUBMITTED',
  REGISTRATION_RESUBMITTED: 'REGISTRATION_RESUBMITTED',
  VERIFICATION_STATUS_CHANGED: 'VERIFICATION_STATUS_CHANGED',

  // Land
  LAND_HOLDING_ADDED: 'LAND_HOLDING_ADDED',
  LAND_HOLDING_UPDATED: 'LAND_HOLDING_UPDATED',
  LAND_HOLDING_REMOVED: 'LAND_HOLDING_REMOVED',

  // Farmer booking (Phase 4)
  BOOKING_CREATED: 'BOOKING_CREATED',
  BOOKING_CANCELLED: 'BOOKING_CANCELLED',

  // Procurement centre operations (§40)
  SESSION_OPENED: 'SESSION_OPENED',
  SESSION_CLOSED: 'SESSION_CLOSED',
  SLOT_CREATED: 'SLOT_CREATED',
  SLOT_UPDATED: 'SLOT_UPDATED',
  BOOKING_ARRIVED: 'BOOKING_ARRIVED',
  BOOKING_CHECKED_IN: 'BOOKING_CHECKED_IN',
  CROP_VERIFIED: 'CROP_VERIFIED',
  QUALITY_ASSESSED: 'QUALITY_ASSESSED',
  WEIGHT_RECORDED: 'WEIGHT_RECORDED',
  PROCUREMENT_CONFIRMED: 'PROCUREMENT_CONFIRMED',
  PAYMENT_INITIATED: 'PAYMENT_INITIATED',
  PAYMENT_COMPLETED: 'PAYMENT_COMPLETED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  // Phase 8 settlement
  PAYMENT_CREATED: 'PAYMENT_CREATED',
  PAYMENT_PROCESSING: 'PAYMENT_PROCESSING',
  PAYMENT_SUCCEEDED: 'PAYMENT_SUCCEEDED',
  PAYMENT_RETRY: 'PAYMENT_RETRY',
  PAYMENT_VIEWED: 'PAYMENT_VIEWED',
  PAYMENT_RECONCILIATION_REQUIRED: 'PAYMENT_RECONCILIATION_REQUIRED',

  // Cold storage (demo addition)
  COLD_STORAGE_RESERVED: 'COLD_STORAGE_RESERVED',

  // Quality intelligence + queue (Phase 7)
  QUALITY_PREDICTION_REQUESTED: 'QUALITY_PREDICTION_REQUESTED',
  PROCESSING_ESTIMATE_OVERRIDDEN: 'PROCESSING_ESTIMATE_OVERRIDDEN',
  QUEUE_CANDIDATE_SELECTED: 'QUEUE_CANDIDATE_SELECTED',
  QUEUE_CANDIDATE_REMOVED: 'QUEUE_CANDIDATE_REMOVED',
  QUEUE_CANDIDATE_REQUEUED: 'QUEUE_CANDIDATE_REQUEUED',
  WORKSTATION_STATUS_CHANGED: 'WORKSTATION_STATUS_CHANGED',

  // Administration (Phase 12)
  DATA_EXPORTED: 'DATA_EXPORTED',

  // Farmer verification review (District Admin, Phase 14)
  REVIEW_STARTED: 'REVIEW_STARTED',
  REVIEW_RELEASED: 'REVIEW_RELEASED',
  VERIFICATION_APPROVED: 'VERIFICATION_APPROVED',
  CORRECTION_REQUESTED: 'CORRECTION_REQUESTED',
  VERIFICATION_REJECTED: 'VERIFICATION_REJECTED',

  // Documents
  DOCUMENT_UPLOADED: 'DOCUMENT_UPLOADED',
  DOCUMENT_REPLACED: 'DOCUMENT_REPLACED',
  DOCUMENT_DELETED: 'DOCUMENT_DELETED',
  DOCUMENT_REVIEWED: 'DOCUMENT_REVIEWED',
  DOCUMENT_ACCESSED: 'DOCUMENT_ACCESSED',

  // Government messages (Notifications phase, §25)
  FARMER_MESSAGE_PUBLISHED: 'FARMER_MESSAGE_PUBLISHED',

  // Feedback, grievances, helpline, schemes (§41)
  FEEDBACK_CREATED: 'FEEDBACK_CREATED',
  GRIEVANCE_CREATED: 'GRIEVANCE_CREATED',
  GRIEVANCE_STATUS_CHANGED: 'GRIEVANCE_STATUS_CHANGED',
  GRIEVANCE_ASSIGNED: 'GRIEVANCE_ASSIGNED',
  GRIEVANCE_ESCALATED: 'GRIEVANCE_ESCALATED',
  GRIEVANCE_RESPONSE_ADDED: 'GRIEVANCE_RESPONSE_ADDED',
  GRIEVANCE_NOTE_ADDED: 'GRIEVANCE_NOTE_ADDED',
  HELPLINE_CREATED: 'HELPLINE_CREATED',
  HELPLINE_UPDATED: 'HELPLINE_UPDATED',
  HELPLINE_VERIFIED: 'HELPLINE_VERIFIED',
  SCHEME_CREATED: 'SCHEME_CREATED',
  SCHEME_UPDATED: 'SCHEME_UPDATED',
  SCHEME_PUBLISHED: 'SCHEME_PUBLISHED',
  SCHEME_ARCHIVED: 'SCHEME_ARCHIVED',
  FAQ_CREATED: 'FAQ_CREATED',
  FAQ_UPDATED: 'FAQ_UPDATED',

  // Provisioning and access
  STAFF_ASSIGNED: 'STAFF_ASSIGNED',
  ADMIN_CREATED: 'ADMIN_CREATED',
  ACCESS_DENIED: 'ACCESS_DENIED',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];

/**
 * Values that must never reach an audit row, a log line or an error body.
 * Enforced by the redacting logger and the audit service.
 */
export const NEVER_LOG_KEYS: readonly string[] = [
  'otp',
  'otp_code',
  'otpCode',
  'token',
  'access_token',
  'accessToken',
  'refresh_token',
  'refreshToken',
  'authorization',
  'password',
  'service_role',
  'serviceRoleKey',
  'SUPABASE_SERVICE_ROLE_KEY',
  'apikey',
  'aadhaar',
  'aadhaarNumber',
  'aadhaar_number',
];
