-- ===========================================================================
-- Arrival confirmation OTP: staff can no longer mark a booking ARRIVED with a
-- single click and no evidence the farmer is actually present. The code is
-- generated by the database itself, the same way booking_reference already
-- is (`default ... nextval(...)`) — here with `random()` instead of a
-- sequence, since it has to be unpredictable rather than sequential. It is
-- shown only to the farmer (their own booking) and consumed by
-- `arrival_otp_verified_at`, which the app sets once staff enter it
-- correctly, before the existing BOOKED -> ARRIVED transition proceeds.
-- ===========================================================================

alter table public.bookings
  add column arrival_otp_code text not null default lpad((floor(random() * 10000))::int::text, 4, '0'),
  add column arrival_otp_verified_at timestamptz;

comment on column public.bookings.arrival_otp_code is
  'A 4-digit code shown only to the farmer, read aloud to centre staff on arrival and checked before BOOKED -> ARRIVED is allowed.';
comment on column public.bookings.arrival_otp_verified_at is
  'Set once staff enter the correct arrival_otp_code. Null means arrival has not been confirmed yet.';
